---
# Source: postgresql/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: postgres-postgresql
  namespace: "default"
  labels:
    app.kubernetes.io/instance: postgres
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/version: 16.1.0
    helm.sh/chart: postgresql-13.2.5
type: Opaque
data:
  postgres-password: "SGlFSktPVDlsbQ=="
  # We don't auto-generate LDAP password when it's not provided as we do for other passwords
